name: CI/CD Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Azure Logout to clear cached credentials, just in case
    - name: Azure Logout (to clear cache)
      run: az logout || true

    # Azure Login using the Service Principal credentials from secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Debug step to ensure secrets are correctly passed
    - name: Debug environment variables
      run: printenv | grep 'AZURE'

    # Upload the frontend to Azure Blob Storage
    - name: Deploy to Azure Storage
      run: |
        az storage blob upload-batch -d '$web' -s './Frontend' --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --auth-mode login
